def goAnimeOfflineRepository = new File(
    gradle.gradleUserHomeDir,
    'offline-goanime-maven'
)
def goAnimeOfflineRepositoryUri = goAnimeOfflineRepository.toURI()

settingsEvaluated { settings ->
    try {
        settings.dependencyResolutionManagement.repositories.maven {
            name = 'GoAnimeOfflineDelta'
            url = goAnimeOfflineRepositoryUri
        }
    } catch (MissingPropertyException ignored) {
        throw new GradleException(
            'GoAnime offline Maven delta requires dependencyResolutionManagement.'
        )
    }
}
